### ISSUE TITLE
Instruction

### ISSUE THREAD

**Issue by fulldecent** [AndyStricker/FastXLSX#1]
Please provide a simple usage instruction showing how to open XLSX and spit out TSV. Would be wonderful if this showed how to do this for both sheets in a workbook.

**Comment by AndyStricker** [comment]
Documented it both in README and in xslx-to-csv.py script.

**Comment by fulldecent** [comment]
FYI to others: I had to do this to make it work:

```
cp */* .
python xlsx-to-csv.py YOUR_EXCEL_FILE.xslx YOUR_WORKSHEET_NAME
```
